version: '3'
services:
    web:
        # docker image build -t warehouse .
        image: warehouse
        ports:
        - "8000:80"
    db:
        image: mysql:5.6
        environment: 
            MYSQL_USER: admin
            MYSQL_PASSWORD: root
            MYSQL_DATABASE: oswa_inv
            MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
